### ISSUE TITLE
No results

### ISSUE THREAD

**Issue by greenozon** [Bioruebe/spoondec#2]
Using this tool, got this response, how could I understand if this is an issue or it's very old Spoon?

```
Opening installer
[ERROR] No files could be found in the intaller. Either the file is not a Spoon Installer or it is not supported.

```

**Comment by Bioruebe** [comment]
You can send me the file, so I can take a look.

**Comment by greenozon** [comment]
hmm I"m not sure I could easily find it after 1 year passed...

**Comment by Bioruebe** [comment]
Sorry, I didn't have much time to maintain my open source projects during the last year.

If it's not important anymore, you can close the issue.

**Comment by greenozon** [comment]
Thanks! will reopen in a chance of luck
goodluck!
